# Generated by Django 6.0.7 on 2026-07-30 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('dek', models.CharField(help_text='One-sentence summary shown on listings.', max_length=300)),
                ('body', models.TextField(help_text='Leave a blank line between paragraphs.')),
                ('category', models.CharField(choices=[('Business', 'Business'), ('Markets', 'Markets'), ('Leadership', 'Leadership'), ('Technology', 'Technology'), ('Money', 'Money')], default='Business', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
